# Generated by Django 5.2.7 on 2025-10-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Added'), ('REMOVE', 'Removed')], max_length=10),
        ),
    ]
