# Generated by Django 5.2.7 on 2025-10-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='menuitem',
        ),
    ]
