# Generated by Django 5.2.7 on 2025-10-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_menu_item_orderitem_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='menu_item',
        ),
    ]
