# Generated by Django 5.2.7 on 2025-11-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_item_status_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
